ERROR    test-logger:print.py:18 Traceback with variables (most recent call last):
      File "...omitted for tests only.../tests/test_print.py", line 96, in test_logger_as_file
        f(10)
          caplog = <_pytest.logging.LogCaptureFixture object at 0x...omitted for tests only...>
      File "...omitted for tests only.../tests/test_print.py", line 109, in f
        return n / 0
          n = 10
    builtins.ZeroDivisionError: division by zero
